---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-claim
  namespace: gitlab-namespace
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: gitlab-namespace
  labels:
    app: gitlab
spec:
  ports:
    - port: 5432
  selector:
    app: gitlab
    tier: postgreSQL
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresql
  namespace: gitlab-namespace
  labels:
    app: gitlab
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
        tier: postgreSQL
    spec:
      containers:
        - image: postgres:9.6.2-alpine
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: gitlabuser
            - name: POSTGRES_DB
              value: gitlab_database
            - name: POSTGRES_PASSWORD
              value: gitlabpassword
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgres-claim
