apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
  namespace: gitlab-namespace
stringData:
  gitlab.rb: |-
    external_url 'https://example.com'
    registry_external_url 'https://registry.example.com'
    postgresql['enable'] = false
    redis['enable'] = false
    gitlab_rails['gitlab_default_can_create_group'] = false
    gitlab_rails['gitlab_shell_ssh_port'] = 30022
    gitlab_rails['db_encoding'] = "utf8"
    gitlab_rails['db_database'] = "gitlab_database"
    gitlab_rails['db_username'] = "gitlabuser"
    gitlab_rails['db_password'] = "gitlabpassword"
    gitlab_rails['db_host'] = "ext_db_ip"
    gitlab_rails['db_port'] = 5432
    gitlab_rails['redis_host'] = "redis-cluster-ip-service"
    gitlab_rails['redis_port'] = 6379
    nginx['listen_port'] = 80
    nginx['listen_https'] = false
    ####
    registry_nginx['listen_port'] = 4567
    registry_nginx['listen_https'] = false
    ####
    gitlab_rails['smtp_enable'] = true
    gitlab_rails['smtp_address'] = "smtp.example.com"
    gitlab_rails['smtp_port'] = 25
    gitlab_rails['smtp_domain'] = "example.com"
    gitlab_rails['smtp_tls'] = false;
    gitlab_rails['smtp_openssl_verify_mode'] = 'none'
    gitlab_rails['smtp_enable_starttls_auto'] = false
    gitlab_rails['smtp_ssl'] = false
    gitlab_rails['smtp_force_ssl'] = false
    gitlab_rails['gitlab_email_from'] = 'noreply@example.com'
    gitlab_rails['gitlab_email_reply_to'] = 'noreply@example.com'
    ###
    prometheus_monitoring['enable'] = false
