apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-admin
  namespace: gitlab-namespace

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gitlab-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: gitlab-admin
  namespace: gitlab-namespace

---

apiVersion: v1
kind: Service
metadata:
  name: gitlab-cluster-ip-service
  namespace: gitlab-namespace
  labels: 
    app: gitlab
spec:
  type: NodePort
  selector:
    app: gitlab
    tier: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80 #port in the service - any outside object accesses through this port
    targetPort: 80
    nodePort: 31800  
---

apiVersion: v1
kind: Service
metadata:
  name: gitlab-registry-service
  namespace: gitlab-namespace
  labels:
    app: gitlab
spec:
  type: NodePort
  selector:
    app: gitlab
    tier: frontend
  ports:
  - name: registry
    protocol: TCP
    port: 4567 #port in the service - any outside object accesses through this port
    targetPort: 4567
    nodePort: 31700  

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-claim
  namespace: gitlab-namespace
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-credentials-claim
  namespace: gitlab-namespace
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab-namespace
  labels:
    app: gitlab
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
        tier: frontend
    spec:
      containers:
        - image: gitlab/gitlab-ee:latest 
          name: gitlab
          ports:
            - name: registry
              containerPort: 5000
            - name: gitlab
              containerPort: 80
            - name: ssh
              containerPort: 22
          volumeMounts:
            - name: gitlab-data 
              mountPath: /var/opt/gitlab
            - name: gitlab-credentials 
              mountPath: /etc/gitlab
            - name: config
              mountPath: /etc/gitlab/gitlab.rb
              subPath: gitlab.rb       #stores all the configuration in a path gitlab_configuration on the nfs
      volumes:
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-claim
        - name: gitlab-credentials
          persistentVolumeClaim:
            claimName: gitlab-credentials-claim
        - name: config
          secret:
            secretName: gitlab-secrets
      imagePullSecrets:
      - name: default-secret
